config/routes.rb
AppfirstAlerting::Application.routes.draw do
  resources :requests


  resources :alerts

  root :to => "alerts#index"
  match "/call" => "application#call", :via => :get
  match "/init" => "application#init", :via => :get
  match "/new_alert" => "alerts#new"
  match "/new_request" => "requests#new"
  match "/populate_database" => "application#populate_database"
  match "/toggle_error" => "application#toggle_error"
end

app/models/request.rb
class Request
  include Mongoid::Document
  field :server_name, type: String
  field :server_id, type: String
  field :attr_name, type: String
  field :running, type: Boolean, default: false

  attr_accessible :server_name, :server_id, :attr_name, :running

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  helper_method :new


  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @requests }
    end
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
    @request = Request.all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @request }
    end
  end

  def new
    @request = Request.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end

  
  end

  # GET /requests/1/edit
  def edit
    @request = Request.find(params[:id])
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(params[:request])

    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render json: @request, status: :created, location: @request }
      else
        format.html { render action: "new" }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /requests/1
  # PUT /requests/1.json
  def update
    @request = Request.find(params[:id])

    respond_to do |format|
      if @request.update_attributes(params[:request])
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request = Request.find(params[:id])
    @request.destroy

    respond_to do |format|
      format.html { redirect_to :root }
      format.json { head :no_content }
    end
  end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<% @request = Request.new %>

<%= form_for(@request) do |f| %>

  <% $i = 0 %>
  <% servers = Array.new %>
  <% Server.each do |s| %>
    <% servers[$i] = [s.nickname, s.server_id]%>
    <% $i += 1 %>
   <% end %>

  <% $i = 0 %>
  <% attrs = Array.new %>
  <% Attribute.each do |a| %>
  <% attrs[$i] = [a.name, a.name]%>
  <% $i += 1 %>
   <% end %>
   <center>
  <div class="field">
    <%= f.select :server_id, servers%><br />
  </div>

 <div class="field">
    <%= f.select :attr_name, attrs%><br />
  </div>

  <div class="actions">
  	<%= f.submit %>
  </div>
</center>
  <% end %>

app/views/requests/_showall.html.erb
<table class = "table table-striped table-hover table-condensed">
	<tr>
		<th>
		<th>
		<th>Id</th>
		<th>Attribute</th>
		<th>
	</tr>

<% Request.each do |r| %>
	<tr onclick="vis3(<%= r.server_id %>, '<%= r.server_id %>', '<%= r.attr_name %>');">
		<td></td>
		<td></td>
		<td><%= r.server_id %></td>
		<td><%= r.attr_name %></td>
		<td><%= link_to 'delete', r, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	</tr>
<% end %>

</table>

app/views/requests/edit.html.erb
<h1>Editing request</h1>

<%= render 'form' %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<h1>Listing requests</h1>

<table>
  <tr>
    <th>Server name</th>
    <th>Server</th>
    <th>Attr name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @requests.each do |request| %>
  <tr>
    <td><%= request.server_name %></td>
    <td><%= request.server_id %></td>
    <td><%= request.attr_name %></td>
    <td><%= link_to 'Show', request %></td>
    <td><%= link_to 'Edit', edit_request_path(request) %></td>
    <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Request', new_request_path %>