config/routes.rb
AppfirstAlerting::Application.routes.draw do
  resources :requests


  resources :alerts

  root :to => "alerts#index"
  match "/call" => "application#call", :via => :get
  match "/init" => "application#init", :via => :get
  match "/new_alert" => "alerts#new"
  match "/new_request" => "requests#new"
  match "/populate_database" => "application#populate_database"
  match "/toggle_error" => "application#toggle_error"
end

app/models/alert.rb
class Alert
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :server_name, type: String
  field :server_id, type: String
  field :time_stamp, type: Integer
  field :attr, type: String

  attr_accessible :server_name, :server_id, :time_stamp, :attr, :reason
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  require "base64"
  require "json"
  require "httparty"
  require 'ruby-standard-deviation'
  require 'statistics2'

  layout nil
  layout 'application', :except => :show

  def index
    @alerts = Alert.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @alerts }
    end
  end
 
  def show
    @alert = Alert.find(params[:id])

    # respond_to do |format|
    #   format.html { render :layout => false, show => true } # your-action.html.erb
    # end

    render "show", :layout => false

  end

  def new
    logger.debug(session[:server_id])
    @alert = Alert.new
    @alert.server_id = session[:server_id]
    @alert.save
  end

  def create
    @alert = Alert.new(params[:alert])

    respond_to do |format|
      if @alert.save
        format.html { redirect_to @alert, notice: 'Alert was successfully created.' }
        format.json { render json: @alert, status: :created, location: @alert }
      else
        format.html { render action: "new" }
        format.json { render json: @alert.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @alert = Alert.find(params[:id])

    respond_to do |format|
      if @alert.update_attributes(params[:alert])
        format.html { redirect_to @alert, notice: 'Alert was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @alert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alerts/1
  # DELETE /alerts/1.json
  def destroy
    @alert = Alert.find(params[:id])
    @alert.destroy

    respond_to do |format|
      format.html { redirect_to alerts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/views/alerts/_modal.html.erb
<div class="modal-header">
      <a class="close" data-dismiss="modal">×</a>
      <h3>Alert Information</h3>
</div>
<div class="modal-body">
      
  <p>
    <b>Server name:</b>
    <%= @alert.server_name %>
  </p>
  
  <p>
    <b>Server:</b>
    <%= @alert.server_id %>
  </p>
  
  <p>
    <b>Time stamp:</b>
    <%= @alert.time_stamp %>
  </p>
  
  <p>
    <b>Attr:</b>
    <%= @alert.attr %>
  </p>
  
  <p>
    <b>Reason:</b>
    <%= @alert.reason %>
  </p>
  
</div>
<div class="modal-footer">
  <input type="submit" class="btn btn-success" value="Save"/>
</div>

app/views/alerts/_new_alert_to_table.erb
<%= content_tag_for(:tr, @alert) do %>

console.log("this was called")

		<td><%= @alert.server_name %></td>
		<td><%= @alert.server_id %></td>
		<td><%= @alert.attr %></td>
		<td><%= Time.at(@alert.time_stamp) %></td>
		<td><%= link_to 'show', @alert %></td>
		<td><%= link_to 'delete', @alert, method: :delete, data: { confirm: 'Are you sure?' } %></td>

<% end %>

app/views/alerts/_table.html.erb
    <div class="alert-container">
      <table class = "table table-hover table-bordered">
        <thead>
          <th> Server Name </th>
          <th> Server ID </th>
          <th> Attribute </th>
          <th> Alert Time </th>
        </thead>
        <tbody id="table">
 
            <% Alert.each do |alert| %>
            <tr class='alert' onMouseOver="vis4(<%= alert.server_id %>, '<%= alert.server_name %>', '<%= alert.attr %>', '<%= alert.time_stamp.to_i.to_s %>')">
                <td><%= alert.server_name %></td>
                <td><%= alert.server_id %></td>
                <td><%= alert.attr %></td>
                <td><%= Time.at(alert.time_stamp) %></td>
                <td><a class="btn" href="#" onclick="get_modal('<%=alert.id%>')" data-toggle="modal" data-target="#myModal">show</a>
                </td>
                <td><%= link_to 'delete', alert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>

        </tbody>
      </table><!--  End of alert box -->
    </div>

            <%= yield %>

app/views/alerts/edit.html.erb
<h1>Editing alert</h1>

<%= render 'form' %>

<%= link_to 'Show', @alert %> |
<%= link_to 'Back', alerts_path %>

app/views/alerts/new.html.erb
<h1>New alert</h1>

<%= render 'form' %>

<%= logger.debug("porcupine") %>


<%= link_to 'Back', alerts_path %>

app/views/alerts/show.html.erb
<div class="modal-header">
      <a class="close" data-dismiss="modal">×</a>
      <h3>Alert Information</h3>
</div>
<div class="modal-body">
      
  <p>
    <b>Server name:</b>
    <%= @alert.server_name %>
  </p>
  
  <p>
    <b>Server id:</b>
    <%= @alert.server_id %>
  </p>
  
  <p>
    <b>Time stamp:</b>
    <%= Time.at(@alert.time_stamp) %>
  </p>
  
  <p>
    <b>Attribute causing alert:</b>
    <%= @alert.attr %>
  </p>
  
  <script>
    vis5()
  </script>

</div>
<div class="modal-footer">
  <input type="submit" class="btn btn-success" value="Save"/>
</div>